### ISSUE TITLE
Issue with gpg and tty in freight-cache

### ISSUE THREAD

**Issue by ghost** [rcrowley/freight#28]
Hi,

Thank a lot for fright.

I am trying to use it to generate repositories on one of our servers and I can't manage to get GPG signing working. I am not using gpg-agent and whenever I run freight-cache, I get:

  gpg: gpg-agent is not available in this session
  gpg: Sorry, no terminal at all requested - can't get input
  # [freight] couldn't sign the repository, perhaps you need to run
  # [freight] gpg --gen-key and update the GPG setting in 
  # [freight](see freight%285%29 for more information)

It doesn't matter wether I run it directly in the server console, or though SSH or su. Indeed. the `tty' call in the script returns false. It appears that since input is piped into the call to apt_cache (in freight-cache), there is no longer a tty.

If i remove `$(tty -s || echo " --no-tty")' from apt.sh, it works, and I get a prompt for the passphrase.

I guess there is something wrong with my environment as I don't understand how this could work for others (I haven't tried with gpg-agent though).

**Comment by ghost** [comment]
Sorry, I forgot about the first rule of bug reporting...

I am facing this issue on Ubuntu 12.04, using freight 3.0.1 from the package found at http://packages.rcrowley.org/.

**Comment by rcrowley** [comment]
@eolamey does 4e4e678c3ad6509e26f73860368eeb472c094353 fix the issue for you?  I'm a bit perplexed as to how you're seeing it and I'm not but regardless, I believe this will address the issue.

I'll cut a new release when you confirm that it works.

**Comment by ghost** [comment]
Richard, thanks a lot for you answer and patch, which works as expected. I don't understand either how it could work before for everyone else but me, as my environment is pretty standard...

Anyway, thanks again for this.

**Comment by ccollicutt** [comment]
I have the exact same problem.

**Comment by rcrowley** [comment]
I just pushed v0.3.2 to http://packages.rcrowley.org, which includes this fix.  Thanks for the reports!

**Comment by ccollicutt** [comment]
Much appreciated, thanks for the great work -- will be using it today. :)

**Comment by midacts** [comment]
I am running Debian 7.6
I install freight by running the following commands:

```
    wget -O /etc/apt/trusted.gpg.d/rcrowley.gpg http://packages.rcrowley.org/keyring.gpg
    apt-get update
    apt-get -y install freight
```

I am currently running freight version 0.3.5-1

When i run `freight cache`, I still receive the following message:

```
    "gpg: gpg-agent is not available in this session"
```

**Comment by kosty** [comment]
Thanks for freight! It is great!

I seem to run into similar issues with a 

``` sh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04


$ ssh  deploy.host 'dpkg --list | grep freight'
ii  freight                             0.3.4-1                           A modern take on the Debian archive.
$ ssh  deploy.host 'cd ~/incoming && freight-cache -v'
gpg: gpg-agent is not available in this session
gpg: Sorry, no terminal at all requested - can't get input
# [freight] couldn't sign the repository, perhaps you need to run
# [freight] gpg --gen-key and update the GPG setting in 
# [freight] (see freight(5) for more information)
```

The fix https://github.com/rcrowley/freight/commit/4e4e678c3ad6509e26f73860368eeb472c094353 seems to be there

``` sh
$ ssh deploy.host 'grep -B 3 -A 3 -nH TTY /usr/lib/freight/apt.sh' 
/usr/lib/freight/apt.sh:1:TTY="$(tty -s && echo "1" || :)"
/usr/lib/freight/apt.sh-2-
/usr/lib/freight/apt.sh-3-# Fetch the given field from the package's control file.
/usr/lib/freight/apt.sh-4-apt_info() {
--
/usr/lib/freight/apt.sh-181-    } >"$DISTCACHE/Release"
/usr/lib/freight/apt.sh-182-
/usr/lib/freight/apt.sh-183-    # Sign the top-level `Release` file with `gpg`.
/usr/lib/freight/apt.sh:184:    gpg -abs$([ "$TTY" ] || echo " --no-tty") --use-agent -u"$GPG" \
/usr/lib/freight/apt.sh-185-        $([ "$GPG_PASSPHRASE_FILE" ] && echo " --batch --passphrase-fd 1 --passphrase-file $GPG_PASSPHRASE_FILE") \
/usr/lib/freight/apt.sh-186-        -o"$DISTCACHE/Release.gpg" "$DISTCACHE/Release" || {
/usr/lib/freight/apt.sh-187-        cat <<EOF
```

so I'm not sure if that's the same issue or not
